export const DIFFICULTY_PRESETS = ["Easy", "Medium", "Hard"] as const;

export const PLATFORM_PRESETS = [
  "LeetCode",
  "Codeforces",
  "HackerRank",
  "AtCoder",
  "CodeChef",
  "GeeksforGeeks",
  "InterviewBit",
  "Other",
] as const;

export const PATTERN_CATEGORY_PRESETS = [
  "Two Pointers",
  "Sliding Window",
  "Fast & Slow Pointers",
  "Merge Intervals",
  "Cyclic Sort",
  "In-place Linked List Reversal",
  "Binary Search",
  "Modified Binary Search",
  "Breadth-First Search",
  "Depth-First Search",
  "Tree BFS",
  "Tree DFS",
  "Backtracking",
  "Greedy",
  "Dynamic Programming",
  "0/1 Knapsack",
  "Unbounded Knapsack",
  "Divide and Conquer",
  "Topological Sort",
  "Union Find",
  "Trie",
  "Monotonic Stack",
  "Monotonic Queue",
  "Top K Elements",
  "Two Heaps",
  "K-way Merge",
  "Bitwise XOR",
  "Prefix Sum",
  "Matrix Traversal",
  "Graph Traversal",
  "Shortest Path",
  "Minimum Spanning Tree",
  "Segment Tree",
  "Binary Indexed Tree",
  "Math & Geometry",
] as const;

export const TOPIC_PRESETS = [
  "Arrays",
  "Strings",
  "Hash Table",
  "Linked List",
  "Stacks & Queues",
  "Trees",
  "Binary Search Tree",
  "Heaps",
  "Graphs",
  "Tries",
  "Matrix",
  "Sorting",
  "Searching",
  "Recursion",
  "Dynamic Programming",
  "Greedy",
  "Bit Manipulation",
  "Math",
  "Number Theory",
  "Combinatorics",
  "Geometry",
  "Union Find",
  "Segment Tree",
  "Binary Indexed Tree",
  "Design",
  "Simulation",
  "Concurrency",
  "Database",
  "Game Theory",
  "Randomized Algorithms",
] as const;

// Suggestions for the free-form tag field. Users can add any tag; these are
// just common companies that ask DSA questions, offered as autocomplete hints.
export const COMPANY_PRESETS = [
  "Google",
  "Amazon",
  "Microsoft",
  "Meta",
  "Apple",
  "Netflix",
  "Uber",
  "Adobe",
  "Bloomberg",
  "Goldman Sachs",
  "Oracle",
  "Salesforce",
  "Nvidia",
  "Atlassian",
  "Airbnb",
  "LinkedIn",
  "Stripe",
  "Databricks",
  "TikTok",
  "Samsung",
  "Flipkart",
  "Walmart",
  "Cisco",
  "Intel",
  "PayPal",
] as const;

export const COMPLEXITY_PRESETS = [
  "O(1)",
  "O(log n)",
  "O(sqrt(n))",
  "O(n)",
  "O(n log n)",
  "O(n^2)",
  "O(n^3)",
  "O(2^n)",
  "O(n!)",
] as const;

export const LANGUAGE_PRESETS = [
  { label: "Python", value: "python" },
  { label: "C++", value: "cpp" },
  { label: "Java", value: "java" },
  { label: "JavaScript", value: "javascript" },
  { label: "TypeScript", value: "typescript" },
  { label: "Rust", value: "rust" },
  { label: "Go", value: "go" },
  { label: "C", value: "c" },
  { label: "C#", value: "csharp" },
  { label: "Kotlin", value: "kotlin" },
] as const;
